### PR TITLE
c/r: use /proc/self/tid/children instead of pidfile

### LINKED ISSUE #1150: checkpoint failed for trusty and debain image
This is a regression in lxc 2.0.4, checkpoint always failed for trusty instance (also failed for debain/wheezy).

To reproduce the problem:
1. lxc-create -t download -n t2 -- -r trusty -d ubuntu -a amd64
2. edit config file as below
```
# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.arch = x86_64

# Container specific configuration
lxc.rootfs = /var/lib/lxc/t2/rootfs
lxc.rootfs.backend = dir
lxc.utsname = t2

# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:81:48:2e

lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm
lxc.mount.auto = cgroup:mixed
lxc.autodev = 1
lxc.kmsg = 0
lxc.include = /usr/share/lxc/config/common.conf.d/00-lxcfs.conf
```
3.  lxc-checkpoint -n t2 -v -D /tmp/dump -s
4.  lxc-checkpoint -n t2 -v -D /tmp/dump -r -l TRACE -o /tmp/lxc.log

It fail to restore the instance. Error:
```
# console output:
lxc-checkpoint: cgroups/cgfsng.c: cgfsng_create: 1072 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/t2: No such file or directory
root@i-dgvu78h1:~# lxc-checkpoint: criu.c: do_restore: 774 reading restore pid failed
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/systemd//lxc/t2-1
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/cpu//lxc/t2-1
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/freezer//lxc/t2-1
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/devices//lxc/t2-1
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/perf_event//lxc/t2-1
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/memory//lxc/t2-1
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/hugetlb//lxc/t2-1
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/blkio//lxc/t2-1
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/cpuset//lxc/t2-1
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/pids//lxc/t2-1
lxc-checkpoint: cgroups/cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/net_cls//lxc/t2-1

# lxc.log
 lxc-checkpoint 20160825193919.889 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for delete_module action 327681
 lxc-checkpoint 20160825193919.889 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for delete_module action 327681
 lxc-checkpoint 20160825193919.889 INFO     lxc_seccomp - seccomp.c:parse_config_v2:456 - Merging in the compat seccomp ctx into the main one
 lxc-checkpoint 20160825193919.889 DEBUG    lxc_start - start.c:setup_signal_fd:290 - sigchild handler set
 lxc-checkpoint 20160825193919.889 INFO     lxc_start - start.c:lxc_init:489 - 't2' is initialized
 lxc-checkpoint 20160825193919.889 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for t2
 lxc-checkpoint 20160825193919.889 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1072 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/t2: No such file or directory
 lxc-checkpoint 20160825193919.890 INFO     lxc_criu - criu.c:exec_criu:422 - execing: /usr/local/sbin/criu restore --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /tmp/dump3 -o /tmp/dump3/restore.log -vvvvvv --root /usr/lib/x86_64-linux-gnu/lxc --restore-detached --restore-sibling --pidfile criu_restore_8PisRV --cgroup-root /lxc/t2-1 --ext-mount-map console: --veth-pair eth0=veth2QE8R3@lxcbr0
 lxc-checkpoint 20160825193920.138 ERROR    lxc_criu - criu.c:do_restore:774 - reading restore pid failed
 lxc-checkpoint 20160825193920.138 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 't2', config section 'lxc'
 lxc-checkpoint 20160825193920.641 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 't2', config section 'lxc'
 lxc-checkpoint 20160825193921.143 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/systemd//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.143 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/systemd//lxc/t2-1
 lxc-checkpoint 20160825193921.143 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/cpu//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.143 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/cpu//lxc/t2-1
 lxc-checkpoint 20160825193921.143 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/freezer//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.143 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/freezer//lxc/t2-1
 lxc-checkpoint 20160825193921.143 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/devices//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.144 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/devices//lxc/t2-1
 lxc-checkpoint 20160825193921.144 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/perf_event//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.144 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/perf_event//lxc/t2-1
 lxc-checkpoint 20160825193921.144 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.144 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/memory//lxc/t2-1
 lxc-checkpoint 20160825193921.144 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/hugetlb//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.144 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/hugetlb//lxc/t2-1
 lxc-checkpoint 20160825193921.144 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/blkio//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.144 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/blkio//lxc/t2-1
 lxc-checkpoint 20160825193921.145 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/cpuset//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.145 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/cpuset//lxc/t2-1
 lxc-checkpoint 20160825193921.145 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/pids//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.145 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/pids//lxc/t2-1
 lxc-checkpoint 20160825193921.145 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:948 - cgroup_rmdir: failed to delete /sys/fs/cgroup/net_cls//lxc/t2-1: Device or resource busy
 lxc-checkpoint 20160825193921.145 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:983 - Error destroying /sys/fs/cgroup/net_cls//lxc/t2-1
```

My env:
ubuntu 16.04, 4.4.0-34-generic
lxc 2.0.4, lxcfs 2.0.3, criu 2.5

### PR DESCRIPTION
**Pull request by tych0**
All we really needed a unique temp file for was passing the pid. Since CRIU
opened this with O_EXCL | O_CREAT, this was "safe" (users could still
overwrite it afterwards, but the monitor would immediately die since the
only valid number in there was the init process).

In any case, we can just read /proc/self/tid/children, which lists the
child process.

Closes #1150

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

File: src/lxc/criu.c [hunk 1]
```diff
@@ -742,8 +733,9 @@ static void do_restore(struct lxc_container *c, int status_pipe, struct migrate_
 		}
 
 		if (WIFEXITED(status)) {
+			char buf[4096];
```
Comment (brauner) [inline src/lxc/criu.c]: Hm, maybe we can make the buffer a little smaller. :)

```
/* /proc + /self + /int64_as_str + /children + \0 */
size_t len = 5 + 5 + 21 + 9 + 1;
char path[len];
```

Comment (tych0) [inline src/lxc/criu.c]: We use the buffer in the other if branch too, so I'm just re-using the same buffer.

Comment (brauner) [inline src/lxc/criu.c]: Ah, thanks. :)
