### PR TITLE
confile: fix parsing

### LINKED ISSUE #1595: lxc-start-ephemeral in 2.0.8 creates configuration it can't parse
# Required information

 * Distribution: Ubuntu 14.04
 * Distribution version: Ubuntu 14.04.5 LTS
 * The output of
   * `lxc-start --version` : 2.0.8
   * `uname -a` : Linux vagrant-ubuntu-trusty-64 3.13.0-119-generic #166-Ubuntu SMP Wed May 3 12:18:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

# Issue description

Given I have a container and I want to create a new ephemeral container from it, a configuration is being created, that leads to lxc erroring out on parsing it and thus lxc tooling not being able to interact with the new container. This wasn't the case in 2.0.7 but is now the case in 2.0.8.

# Steps to reproduce

`lxc-create -n foobar -t ubuntu`
`lxc-start-ephemeral -n foobar-ephemeral -o foobar -d`
`lxc-ls -f` leads to:
`lxc-ls: parse.c: lxc_file_for_each_line: 57 Failed to parse config: lxc.ephemeral =`

# Information to attach

- the configuration file looks as follows
```
cat /var/lib/lxc/foobar-ephemeral/config
# Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
# Parameters passed to the template:
# Template script checksum (SHA-1): 4d7c613c3c0a0efef4b23917f44888df507e662b
# For additional config options, please look at lxc.container.conf(5)
# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)
# Common configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
# Container specific configuration
lxc.rootfs.backend = dir
lxc.arch = amd64
# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:9b:4e:ab
lxc.utsname =
lxc.utsname = foobar-ephemeral
lxc.rootfs =
lxc.rootfs = /var/lib/lxc/foobar-ephemeral/rootfs
lxc.network.0.hwaddr = 00:16:3e:6f:fd:69
lxc.hook.pre-mount =
lxc.hook.pre-mount = /var/lib/lxc/foobar-ephemeral/pre-mount
lxc.ephemeral =
lxc.ephemeral = 1
```

I believe the line `lxc.ephemeral =` is the one triggering the configuration parse issue.

### PR DESCRIPTION
**Pull request by brauner**
So this has grown into a major rework of the configuration system. My reasons for this are plenty most of all:
- there were/are a bunch of configuration items that had a set but no get method
- there were a bunch of configuration items that could not be cleared via the api
- adding new configuration items was error prone since the set method was enforced by the callback system but neither the get nor clear methods were

This changes to a new callback-based configuration system that is enforced via the lxc_config_t struct. If someone wants to implement a new configuration item things should now be more straightforward. To add a new configuration items one needs to:
- create a new member in the lxc_config_t struct and implement
  1. a set method
  2. a get method
  3. a clear method
simple as that.

The rework is also necessary because we recently fixed a bug whereby lots of config items could be set but couldn't be unset via clear_config_item(). This was especially problematic when copying containers because the config items where stacked onto each other if they were changed. The same problem for api calls to clear_config_item() + set_config_item(). The fix however did not take into account that this means that whitespace character for all of these config items need to be accounted for. This commit does.

Closes #1595.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
Actually I'm not sure whether we should consider whitespace a problem or not. I mean one could also make the reasonable argument that it must always be `lxc.some_int_value =` and not `lxc.some_int_value=\n\t`. The latter allows for more flexibility. @stgraber, @hallyn

**Comment by brauner** [comment]
We should only consier `!value || !strlen(value)` valid.

**Comment by stgraber** [comment]
Looks good to me but will give some time for @hallyn to take a look

**Comment by brauner** [comment]
All of the changes are very very incremental which is intentional so that we reduce regression potential as much as possible.

**Comment by hallyn** [comment]
Dude.

**Comment by hallyn** [comment]
Are there any libc's out there which will crash on free(NULL)?

**Comment by brauner** [comment]
@hallyn, never heard of such a thing but then we would crash in a bunch of places. :)

Also, what? Too much little commits. I actually think this provides some value given that the whole config handling has gotten really mucky. When people implemented something new, they often forgot either the getter, the clearer or both. I think this way of using the jump table for everything makes it very straightforward to grasp what is needed and how this works. But feel free to disagree and argue against it. The amount of commits should play no role in the decision. :)

**Comment by hallyn** [comment]
No no i like the bunch of little commits.  It's looking for the more complicated/longer ones in the set of little commits that's stressful :)

Ok - I thought I had seen us crash on free(NULL) before, but can't reproduce it with my libc's here, so let's assume i'm wrong.  Crazy assumption.

**Comment by brauner** [comment]
So one of the bigger commits is that I implemented a new parser for lxc.id_map and a getter for lxc.id_map which we didn't have before.

File: src/lxc/confile.c [hunk 1]
```diff
@@ -2967,6 +2967,54 @@ static int lxc_get_item_network(struct lxc_conf *c, char *retv, int inlen)
 	return fulllen;
 }
 
+static int lxc_get_idmaps(struct lxc_conf *c, char *retv, int inlen)
+{
+	struct lxc_list *it;
+	int len, listlen, ret;
+	int fulllen = 0;
```
Comment (hallyn) [inline src/lxc/confile.c]: What's up with fulllen?

Comment (brauner) [inline src/lxc/confile.c]: What do you mean? The `strprint()` function expects `len`, `fulllen` and a bunch of others to be defined. I don't find it the best way to do it either.

**Comment by hallyn** [comment]
Quoting Christian Brauner (notifications@github.com):
> brauner commented on this pull request.
> 
> 
> 
> > @@ -2967,6 +2967,54 @@ static int lxc_get_item_network(struct lxc_conf *c, char *retv, int inlen)
>  	return fulllen;
>  }
>  
> +static int lxc_get_idmaps(struct lxc_conf *c, char *retv, int inlen)
> +{
> +	struct lxc_list *it;
> +	int len, listlen, ret;
> +	int fulllen = 0;
> 
> What do you mean? The `strprint()` function expects `len`, `fulllen` and a bunch of others to be defined. I don't find it the best way to do it either.

D'oh, I (a) misread the s*print and (b) forgot we had that
abomination :)

thanks.
