### PR TITLE
conf, criu: add make_anonymous_mount_file()

### LINKED ISSUE #1296: [lxc-android] Can't bind mount inside container
Hello,

For lxc on android, when I try to bind mount the directory inside container.

```
lxc.mount.entry = /system system/ none bind,optional,create=dir
```

it fails with cryptic error

```
lxc_conf - conf.c:write_mount_file:1960 - tmpfile error: m                       
lxc_conf - conf.c:lxc_setup:3731 - failed to setup the mount entries for 'system'
```

I am not really sure whatever is "tmpfile error: m"?

### PR DESCRIPTION
**Pull request by brauner**
Before we used tmpfile() to write out mount entries for the container. This
requires a writeable /tmp file system which can be a problem for Android where
this filesystem is not necessarily present. This commit switches from tmpfile()
to using the memfd_create() syscall. It allows us to create an anonymous tmpfs
file (And is somewhat similar to mmap().) which is automatically deleted as
soon as any references to it are dropped.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

Closes #1296.

### CODE REVIEW

**Comment by brauner** [comment]
Let's see if all architectures like this.

**Comment by stgraber** [comment]
This effectively means that LXC won't work on anything prior to 3.17 though, right?

If so, that's not acceptable.

**Comment by brauner** [comment]
Yeah, I will add fallback code for that case. I just want to see whether our Android is in general fine with this.

**Comment by stgraber** [comment]
Well, no shipping Android kernels have that syscall, so the direct syscall will "work" with bionic but won't give you much :)

**Comment by brauner** [comment]
*sigh*, Android. Well, `memfd_create()` has its value in any case as it allows us to avoid `/tmp` in most cases.

**Comment by brauner** [comment]
Well, `Marshmallow` and `Nougat` should have `memfd_create()` supporrt. :)

**Comment by stgraber** [comment]
@brauner nope, they ship with a 3.12 kernel.

**Comment by brauner** [comment]
*sigh* again. In any case, I added fallback code in case the `memfd_create()` syscall is not implemented. I still see value in not relying on `/tmp` being present when the kernel allows us to.

File: src/lxc/conf.c [hunk 1]
```diff
@@ -49,37 +62,25 @@
...
-#include <sys/mount.h>
-#include <sys/mman.h>
-#include <sys/prctl.h>
-
-#include <arpa/inet.h>
-#include <fcntl.h>
-#include <netinet/in.h>
-#include <net/if.h>
-#include <libgen.h>
+#ifdef HAVE_LINUX_MEMFD_H
```
Comment (stgraber) [inline src/lxc/conf.c]: You don't have a configure.ac entry for this

File: src/lxc/conf.c [hunk 2]
```diff
@@ -167,6 +166,57 @@ return -1;
...
+/* memfd_create() */
+#ifndef MFD_CLOEXEC
+#define MFD_CLOEXEC 0x0001U
+#endif
+
+#ifndef MFD_ALLOW_SEALING
+#define MFD_ALLOW_SEALING 0x0002U
+#endif
+
+#ifndef HAVE_MEMFD_CREATE
```
Comment (brauner) [inline src/lxc/conf.c]: Will do.

File: src/lxc/conf.c (hunk 1 above)
Comment (brauner) [inline src/lxc/conf.c]: Will do.

**Comment by brauner** [comment]
@stgraber, this should check for `memfd_create()` in `configure.ac` now.
